project:
  type: website

website:
  title: ""
  navbar:
    right:
      - about.qmd
      - icon: linkedin
        href: https://www.linkedin.com/in/emil-bsaibes/
  
  page-footer:  
    left: "© Emil Bsaibes 2023"

format:
  html:
    theme: cosmo
    css: styles.css

execute:
    freeze: auto