project:
  type: website

website:
  title: "Emil Bsaibes"
  navbar:
    right:
      - text: "Home"
        file: index.qmd
      - text: "About"
        file: about.qmd
      - icon: linkedin
        href: https://www.linkedin.com/in/emil-bsaibes/
  
  page-footer:  
    left: "© Emil Bsaibes 2023"

format:
  html:
    theme: 
      - lux
      - custom.scss
    css: styles.css

execute:
    freeze: auto