---
title: "Defending Your Time"
date: "2024-02-28"
title-block-style: default
categories: [daily routines, worklife, habits, timeblocking]
---

> “All we have to decide is what to do with the time given to us.” 
>
> -- <cite> J.R.R. Tolkein, Fellowship of the Ring. </cite> 

Last month I wrote about making improvements to my running performance. I had to make the time for more strength training required to boost my speed, and strength overall. Fortunately I had some established tools and habits I could lean on to help me, but before we get into them. Let’s discuss what defending your time means. 

Defending your time consists of three things:

1. Deciding how you use your time 
2. Making Time
3. Following through

**Step 1.** 
The easiest of the three. What do you want to do? What are your goals, hobbies, projects, things you need to take care of? People you want to see? Write them down, prioritize them by importance.

**Step 2.** 
Where can you fit these into your schedule? Is there anything you’re doing that is taking time away that you don’t like doing or don’t need to do? This is where I’d start. Scrolling on social media is an easy example from my own experience. A few years ago I deactivated Facebook to simply break the habit of logging in to it as the first thing I did when I turned on my computer. Deactivating was the first step and some anxiety went away after a few days of not being drawn into it. Also I made time for more meaningful things in my life. Last year I deleted my data and account all together. 

“Making time” and “Finding time” do not mean the same thing. “Making time” puts you in control of your intentions and how to use your time. “Finding time” for things gives away your control and forces you to fit stuff in. The day or week isn’t going to go perfectly, things are going to happen that are out of your control and you’ll find that time will fly by and your endeavor will go with it. Making the time is a simple reframing that gives you agency and ownership and permission to say no to things that don't matter. 

**Step 3.** Stick to the plan
This is the hard part. This is where “defending” comes in. A few examples:

- Let’s say you want to start running. You make a goal that you’re going to get up early and go run. You said you were going to run at 6:30AM. It's 6:15 are you going to stay in bed or go get your run in. 
- Let’s say you decide you want better sleep. It’s 10:30 pm and you have already watched an episode of your favorite show. Are you going to bed now or watching another one? Which do you choose?

Who’s in charge in these situations? The simple answer is **YOU**.

## Tools
Defending your time is hard and doesn't get easier the more responsibilities you take on. But there are simple tools and habits that can help you. 

The main two tools I use are simple. My calendar and my journal.

#### Calendar 
My digital calendar is by far the most and easiest to use to make time. It keeps me accountable and sets other’s expectations of my availability. 

The first meetings scheduled on my calendar are my workouts (recurring forever) Next are Focus blocks. In between are short breaks which slide around but they are there as a simple reminder to get up, move, or stretch. 

#### Journal 
This is relatively new. I’ve tried journaling on and off for years but last year I committed to [Bullet Journaling](https://www.youtube.com/watch?v=fm15cmYU0IM) and found it worked well for me. It gave me enough structure but also flexibility to make it my own. 

Besides day to day tasks and reminders, I use it for quotes, notes, random thoughts, doodles. It’s nice to go back and look at them too. I went back and found my son’s diaper and feeding log when he was first born. 

Handwriting is therapeutic too. When life gets busy it's easy to get overwhelmed. Writing my thoughts, notes, reminders gets it out of my head, and relieves some stress. I also love the satisfaction of checking off tasks from my to-do list. 

## My Everyday Time Blocks

Scheduling the time in the calendar one thing but having a purpose for each block is another. I've made a habit of scheduling key parts of my day. These are my most used and recurring. Occasionally they’ll need to shift around. The important thing is that the time block moves, but NOT deleted. 

### Focus Time
This is recurring every day and happens first. I grab my coffee then head to my office. I crack open the journal and reflect on the day before. I like reflecting on the previous day in the morning - usually a night's rest helps filter out a lot of the noise and I can think about only what's most important. Occasionally I’ll reflect in the evening too, just depends on the day.

Then I grab two books - the [Daily Dad](https://store.dailydad.com/products/the-daily-dad-signed-by-ryan-holiday-1?variant=42269682892980/) and the [Daily Stoic](https://store.dailystoic.com/collections/all-books/products/the-daily-stoic-signed-edition). I read the passage for the day from each and jot down my reflection. These ground me and help me focus on what’s most important in my life.

After my daily reflections, I list and prioritize the tasks for the day. Once complete I’m ready to start my work. Morning won!

### Lunch (ie Workout)
Discussed in my last post this is a critical one for me. It’s the first thing I put on any shared or digital calendar.  I get a notification when it's about time to get going. I wrap up whatever I’m doing and get ready to get outside. 

### Wrap Up Time/Logoff
Typically, this is the last thirty minutes of the work day. I wrap up the day with notes which I keep in an electronic format. They are very specific to what I’m working on and most easily referenced that way. The tool doesn’t really matter but currently my go-to is OneNote. I reflect on questions like:

- How did the day go?
- What Happened? (What did I do today?)  
- What’s Left to do? 
- What do I need to follow up on? 

It’s not super formal but I try to keep it organized and include important technical notes and questions to follow up on etc. 

### Study Time (Power Hour)
A few nights a week, after the kids are in bed, I work on a personal project or study up on something new, or write a blog post…I’m in this time block right now! (Gif)

I plan the time and decide the purpose for this time block in the morning. On average I get about an hour for this block if and when it happens. So I need to get going. If I want to maximize the time the last thing I want to do is trying to figure out what I want or need to do with this time. That’s a sure fire way to waste it.  

### Other Focused Time Blocks
If there are tasks that require some intense focus I create similar Power Hours during my the date to get the uninterrupted time I need. Also I’m not shy about reflecting it in my instant messenger status. I put up a “Do Not Disturb” ⛔ or “Focus” with 🎧, and I’ll typically turn off notifications and close my email. Most coworkers and teammates respect it, and don’t expect an immediate response. I’m mindful that I’m part of a team and larger organization so I do resurface at the end of the block to respond to emails, and messages I missed.

## It’s Taken time to get here
Getting to this routine involved, burn-out, trial and error, breaking bad habits, and building the confidence to really take charge of my time. I hope some of the tactics I've implemented inspire you to to examine where you're spending time and use it intentionally. 

Start small and experiement. Focus on one thing you really want to do? Does it fit into your life? If so, build up the habit of doing whatever it is little by little on a regular **sustainable** schedule. I saw a post the other day where someone was talking about building a habit of reading by reading 5 minutes a day. She found the time for 5 minutes and did it. She even gamified it, and tries to keep the streak going.

If your thing doesn’t fit into your life? Ask yourself why? What’s something you can let go? Odds are there is something you’re going to have to say “no” to, to fit this new thing in. This goes back to step one in defending your time. Here are the steps again: 

1. Prioritize what you’re doing on a daily basis. Physically write it down and order it. 
2. put in your face, on your calendar, any where you'll see it to remind you to do it. 
3. Do it. Thinking is done, now actually go. You can do it I believe in you. ❤

# Books
Here are some references that have helped me.

- [Atomic Habits](https://jamesclear.com/atomic-habits) by James Clear
- [Power of Habit](https://www.charlesduhigg.com/the-power-of-habit) by Charles Duhigg
- [First Things First](https://www.amazon.com/First-Things-Stephen-R-Covey/dp/0684802031) by Stephen Covey
- [Daily Dad](https://store.dailydad.com/products/the-daily-dad-signed-by-ryan-holiday-1?variant=42269682892980/) by Ryan Holiday
- [Daily Stoic](https://store.dailystoic.com/collections/all-books/products/the-daily-stoic-signed-edition) by Ryan Holiday
- [The Bullet Journal Method](https://bulletjournal.com/pages/book) by Ryder Carroll